# Repository settings configuration for GitHub
# This file can be used with the GitHub Settings app or as documentation for manual configuration

repository:
  # Repository basic settings
  name: hallucifix
  description: "AI Accuracy Verification Engine - Detect and analyze hallucinations in AI-generated content"
  homepage: "https://hallucifix.com"
  topics:
    - ai
    - hallucination-detection
    - content-verification
    - typescript
    - react
    - supabase
  
  # Repository features
  has_issues: true
  has_projects: true
  has_wiki: false
  has_discussions: true
  has_downloads: true
  
  # Security and analysis features
  security_and_analysis:
    advanced_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled
    dependency_graph:
      status: enabled
    dependabot_security_updates:
      status: enabled
    dependabot_alerts:
      status: enabled
  
  # Merge settings
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  
  # Default branch
  default_branch: main

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
        bypass_pull_request_allowances:
          users: []
          teams: []
      
      # Require status checks
      required_status_checks:
        strict: true
        contexts:
          - "Unit Tests"
          - "Integration Tests"
          - "Security Scan"
          - "Coverage Check"
          - "Build"
          - "Lint"
      
      # Additional protections
      enforce_admins: true
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      
      # Restrict pushes
      restrictions:
        users: []
        teams: ["core-developers"]
        apps: []

  - name: develop
    protection:
      # Require pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      
      # Require status checks
      required_status_checks:
        strict: true
        contexts:
          - "Unit Tests"
          - "Integration Tests"
          - "Build"
          - "Lint"
      
      # Additional protections
      enforce_admins: false
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      
      # Restrict pushes
      restrictions:
        users: []
        teams: ["developers"]
        apps: []