# Codecov Configuration for HalluciFix
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Coverage precision (number of decimal places)
  precision: 2
  
  # Round coverage to nearest integer
  round: down
  
  # Coverage range for color coding
  range: "70...100"
  
  # Global coverage targets
  status:
    project:
      default:
        # Target coverage percentage
        target: 80%
        # Threshold for coverage drop
        threshold: 2%
        # Base branch for comparison
        base: auto
        # Require coverage to pass
        if_ci_failed: error
        # Only check coverage on changed files
        only_pulls: false
        
    patch:
      default:
        # Target coverage for new code
        target: 85%
        # Threshold for new code coverage drop
        threshold: 5%
        # Base branch for comparison
        base: auto
        # Only check coverage on pull requests
        only_pulls: true
        
    changes:
      default:
        # Target coverage for changed lines
        target: 90%
        # Base branch for comparison
        base: auto
        # Only check coverage on pull requests
        only_pulls: true

# Comment configuration for pull requests
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  
  # Show coverage for these paths in comments
  show_carryforward_flags: false

# Ignore paths for coverage calculation
ignore:
  - "node_modules/"
  - "dist/"
  - "build/"
  - "coverage/"
  - "docs/"
  - "scripts/"
  - "supabase/"
  - "e2e/"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/*.d.ts"
  - "**/*.stories.*"
  - "**/*.test.*"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "src/test/"
  - "src/types/"
  - "src/vite-env.d.ts"
  - "src/main.tsx"

# Flag configuration for different test types
flags:
  unit-tests:
    paths:
      - src/
    carryforward: true
    
  integration-tests:
    paths:
      - src/lib/
      - src/hooks/
    carryforward: true
    
  e2e-tests:
    paths:
      - src/components/
      - src/pages/
    carryforward: false

# GitHub integration
github_checks:
  annotations: true

# Notification settings
slack:
  url: "secret:SLACK_WEBHOOK_URL"
  threshold: 1%
  message: "Coverage changed for {{owner}}/{{repo}}"
  only_pulls: false
  flags: null
  paths: null

# Codecov bot behavior
codecov:
  # Require CI to pass before processing coverage
  require_ci_to_pass: true
  
  # Maximum number of builds to wait for
  max_report_age: "24h"
  
  # Disable Codecov's own CI checks
  disable_default_path_fixes: false
  
  # Archive settings
  archive:
    uploads: true

# Pull request annotations
annotations:
  range: "70..100"
  coverage_threshold: 80
  patch_coverage_threshold: 85