# Environment-Specific Secrets Configuration
# This file defines secrets, variables, and access controls for each deployment environment

# Development Environment Configuration
development:
  description: "Development environment for testing and feature development"
  url: "https://dev.hallucifix.com"
  auto_deploy: true
  
  secrets:
    # Database and Backend Services
    VITE_SUPABASE_URL:
      description: "Supabase project URL for development"
      validation_pattern: "^https://[a-z0-9-]+\\.supabase\\.co$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: true
    
    VITE_SUPABASE_ANON_KEY:
      description: "Supabase anonymous key for development"
      validation_pattern: "^eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: true
    
    SUPABASE_SERVICE_ROLE_KEY:
      description: "Supabase service role key for server-side operations"
      validation_pattern: "^eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    DATABASE_URL:
      description: "PostgreSQL database connection string"
      validation_pattern: "^postgresql://[^:]+:[^@]+@[^:]+:[0-9]+/[^?]+$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    # External API Keys
    OPENAI_API_KEY:
      description: "OpenAI API key for AI analysis"
      validation_pattern: "^sk-[A-Za-z0-9]{48}$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    ANTHROPIC_API_KEY:
      description: "Anthropic API key for Claude integration"
      validation_pattern: "^sk-ant-[A-Za-z0-9_-]+$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    # Google OAuth Configuration
    GOOGLE_CLIENT_ID:
      description: "Google OAuth client ID"
      validation_pattern: "^[0-9]+-[a-z0-9]+\\.apps\\.googleusercontent\\.com$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: true
    
    GOOGLE_CLIENT_SECRET:
      description: "Google OAuth client secret"
      validation_pattern: "^GOCSPX-[A-Za-z0-9_-]+$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    # Payment Processing (Test Keys)
    STRIPE_SECRET_KEY:
      description: "Stripe secret key for payment processing (test)"
      validation_pattern: "^sk_test_[A-Za-z0-9]{99}$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    STRIPE_WEBHOOK_SECRET:
      description: "Stripe webhook endpoint secret"
      validation_pattern: "^whsec_[A-Za-z0-9]{32}$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    STRIPE_PUBLISHABLE_KEY:
      description: "Stripe publishable key (test)"
      validation_pattern: "^pk_test_[A-Za-z0-9]{99}$"
      security_level: "low"
      rotation_schedule: "quarterly"
      required: true
    
    # Monitoring and Analytics
    SENTRY_DSN:
      description: "Sentry DSN for error tracking"
      validation_pattern: "^https://[a-f0-9]+@[a-f0-9]+\\.ingest\\.sentry\\.io/[0-9]+$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: false
    
    # Notification Services
    SLACK_WEBHOOK_URL:
      description: "Slack webhook URL for notifications"
      validation_pattern: "^https://hooks\\.slack\\.com/services/[A-Z0-9]+/[A-Z0-9]+/[A-Za-z0-9]+$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: false
    
    # Development-specific
    DEV_LOG_LEVEL:
      description: "Logging level for development"
      validation_pattern: "^(debug|info|warn|error)$"
      security_level: "low"
      rotation_schedule: "never"
      required: false
    
    DEV_API_BASE_URL:
      description: "Base URL for development API"
      validation_pattern: "^https://[a-z0-9.-]+\\.[a-z]{2,}$"
      security_level: "low"
      rotation_schedule: "never"
      required: true

  variables:
    NODE_ENV: "development"
    VITE_APP_ENV: "development"
    VITE_API_BASE_URL: "https://api-dev.hallucifix.com"
    VITE_ENABLE_DEBUG: "true"
    VITE_ENABLE_ANALYTICS: "false"

# Staging Environment Configuration
staging:
  description: "Staging environment for pre-production testing"
  url: "https://staging.hallucifix.com"
  auto_deploy: false
  
  protection_rules:
    required_reviewers: ["staging-approvers", "devops-team"]
    wait_timer: 5  # minutes
    prevent_self_review: false
  
  deployment_branch_policy:
    protected_branches: true
    custom_branches: ["main", "develop"]
  
  secrets:
    # Database and Backend Services
    VITE_SUPABASE_URL:
      description: "Supabase project URL for staging"
      validation_pattern: "^https://[a-z0-9-]+\\.supabase\\.co$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    VITE_SUPABASE_ANON_KEY:
      description: "Supabase anonymous key for staging"
      validation_pattern: "^eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    SUPABASE_SERVICE_ROLE_KEY:
      description: "Supabase service role key for staging"
      validation_pattern: "^eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    DATABASE_URL:
      description: "PostgreSQL database connection string for staging"
      validation_pattern: "^postgresql://[^:]+:[^@]+@[^:]+:[0-9]+/[^?]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    # External API Keys (Production-like)
    OPENAI_API_KEY:
      description: "OpenAI API key for staging analysis"
      validation_pattern: "^sk-[A-Za-z0-9]{48}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    ANTHROPIC_API_KEY:
      description: "Anthropic API key for staging"
      validation_pattern: "^sk-ant-[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    # Google OAuth Configuration
    GOOGLE_CLIENT_ID:
      description: "Google OAuth client ID for staging"
      validation_pattern: "^[0-9]+-[a-z0-9]+\\.apps\\.googleusercontent\\.com$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: true
    
    GOOGLE_CLIENT_SECRET:
      description: "Google OAuth client secret for staging"
      validation_pattern: "^GOCSPX-[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    # Payment Processing (Test Keys)
    STRIPE_SECRET_KEY:
      description: "Stripe secret key for staging (test)"
      validation_pattern: "^sk_test_[A-Za-z0-9]{99}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    STRIPE_WEBHOOK_SECRET:
      description: "Stripe webhook secret for staging"
      validation_pattern: "^whsec_[A-Za-z0-9]{32}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    STRIPE_PUBLISHABLE_KEY:
      description: "Stripe publishable key for staging"
      validation_pattern: "^pk_test_[A-Za-z0-9]{99}$"
      security_level: "medium"
      rotation_schedule: "monthly"
      required: true
    
    # Monitoring and Analytics
    SENTRY_DSN:
      description: "Sentry DSN for staging error tracking"
      validation_pattern: "^https://[a-f0-9]+@[a-f0-9]+\\.ingest\\.sentry\\.io/[0-9]+$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: true
    
    # Notification Services
    SLACK_WEBHOOK_URL:
      description: "Slack webhook for staging notifications"
      validation_pattern: "^https://hooks\\.slack\\.com/services/[A-Z0-9]+/[A-Z0-9]+/[A-Za-z0-9]+$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: true
    
    # Staging-specific
    STAGING_LOG_LEVEL:
      description: "Logging level for staging"
      validation_pattern: "^(info|warn|error)$"
      security_level: "low"
      rotation_schedule: "never"
      required: false
    
    STAGING_API_BASE_URL:
      description: "Base URL for staging API"
      validation_pattern: "^https://[a-z0-9.-]+\\.[a-z]{2,}$"
      security_level: "medium"
      rotation_schedule: "never"
      required: true

  variables:
    NODE_ENV: "staging"
    VITE_APP_ENV: "staging"
    VITE_API_BASE_URL: "https://api-staging.hallucifix.com"
    VITE_ENABLE_DEBUG: "false"
    VITE_ENABLE_ANALYTICS: "true"

# Production Environment Configuration
production:
  description: "Production environment for live application"
  url: "https://hallucifix.com"
  auto_deploy: false
  
  protection_rules:
    required_reviewers: ["production-approvers", "security-team", "devops-lead"]
    wait_timer: 30  # minutes
    prevent_self_review: true
  
  deployment_branch_policy:
    protected_branches: true
    custom_branches: ["main"]
  
  secrets:
    # Database and Backend Services
    VITE_SUPABASE_URL:
      description: "Supabase project URL for production"
      validation_pattern: "^https://[a-z0-9-]+\\.supabase\\.co$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    VITE_SUPABASE_ANON_KEY:
      description: "Supabase anonymous key for production"
      validation_pattern: "^eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    SUPABASE_SERVICE_ROLE_KEY:
      description: "Supabase service role key for production"
      validation_pattern: "^eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    DATABASE_URL:
      description: "PostgreSQL database connection string for production"
      validation_pattern: "^postgresql://[^:]+:[^@]+@[^:]+:[0-9]+/[^?]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    # External API Keys (Production)
    OPENAI_API_KEY:
      description: "OpenAI API key for production analysis"
      validation_pattern: "^sk-[A-Za-z0-9]{48}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    ANTHROPIC_API_KEY:
      description: "Anthropic API key for production"
      validation_pattern: "^sk-ant-[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    # Google OAuth Configuration
    GOOGLE_CLIENT_ID:
      description: "Google OAuth client ID for production"
      validation_pattern: "^[0-9]+-[a-z0-9]+\\.apps\\.googleusercontent\\.com$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    GOOGLE_CLIENT_SECRET:
      description: "Google OAuth client secret for production"
      validation_pattern: "^GOCSPX-[A-Za-z0-9_-]+$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    # Payment Processing (Live Keys)
    STRIPE_SECRET_KEY:
      description: "Stripe secret key for production payments"
      validation_pattern: "^sk_live_[A-Za-z0-9]{99}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    STRIPE_WEBHOOK_SECRET:
      description: "Stripe webhook secret for production"
      validation_pattern: "^whsec_[A-Za-z0-9]{32}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: true
    
    STRIPE_PUBLISHABLE_KEY:
      description: "Stripe publishable key for production"
      validation_pattern: "^pk_live_[A-Za-z0-9]{99}$"
      security_level: "medium"
      rotation_schedule: "monthly"
      required: true
    
    # Monitoring and Analytics
    SENTRY_DSN:
      description: "Sentry DSN for production error tracking"
      validation_pattern: "^https://[a-f0-9]+@[a-f0-9]+\\.ingest\\.sentry\\.io/[0-9]+$"
      security_level: "high"
      rotation_schedule: "quarterly"
      required: true
    
    CODECOV_TOKEN:
      description: "Codecov token for coverage reporting"
      validation_pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
      security_level: "medium"
      rotation_schedule: "quarterly"
      required: false
    
    # Notification Services
    SLACK_WEBHOOK_URL:
      description: "Slack webhook for production alerts"
      validation_pattern: "^https://hooks\\.slack\\.com/services/[A-Z0-9]+/[A-Z0-9]+/[A-Za-z0-9]+$"
      security_level: "high"
      rotation_schedule: "quarterly"
      required: true
    
    SLACK_BOT_TOKEN:
      description: "Slack bot token for automated notifications"
      validation_pattern: "^xoxb-[0-9]+-[0-9]+-[A-Za-z0-9]+$"
      security_level: "high"
      rotation_schedule: "monthly"
      required: false
    
    # Security and Compliance
    SECURITY_SCAN_TOKEN:
      description: "Token for security scanning services"
      validation_pattern: "^[A-Za-z0-9_-]{32,}$"
      security_level: "critical"
      rotation_schedule: "monthly"
      required: false
    
    AUDIT_LOG_ENDPOINT:
      description: "Endpoint for audit log shipping"
      validation_pattern: "^https://[a-z0-9.-]+\\.[a-z]{2,}/[a-z0-9/_-]*$"
      security_level: "high"
      rotation_schedule: "quarterly"
      required: false
    
    # Production-specific
    PROD_LOG_LEVEL:
      description: "Logging level for production"
      validation_pattern: "^(warn|error)$"
      security_level: "low"
      rotation_schedule: "never"
      required: false
    
    PROD_API_BASE_URL:
      description: "Base URL for production API"
      validation_pattern: "^https://[a-z0-9.-]+\\.[a-z]{2,}$"
      security_level: "medium"
      rotation_schedule: "never"
      required: true

  variables:
    NODE_ENV: "production"
    VITE_APP_ENV: "production"
    VITE_API_BASE_URL: "https://api.hallucifix.com"
    VITE_ENABLE_DEBUG: "false"
    VITE_ENABLE_ANALYTICS: "true"

# Access Control Configuration
access_control:
  development:
    admin_access: ["developers", "devops-team"]
    write_access: ["developers", "devops-team", "qa-team"]
    read_access: ["developers", "devops-team", "qa-team", "product-team"]
    
  staging:
    admin_access: ["devops-team", "staging-approvers"]
    write_access: ["devops-team", "staging-approvers", "senior-developers"]
    read_access: ["developers", "devops-team", "qa-team", "product-team", "staging-approvers"]
    
  production:
    admin_access: ["production-approvers", "security-team", "devops-lead"]
    write_access: ["production-approvers", "security-team"]
    read_access: ["devops-team", "security-team", "production-approvers", "compliance-team"]

# Global Configuration
global_settings:
  secret_naming_convention:
    development: "DEV_*"
    staging: "STAGING_*"
    production: "PROD_*"
    shared: "VITE_*"
  
  rotation_policies:
    critical: "monthly"
    high: "monthly"
    medium: "quarterly"
    low: "yearly"
  
  validation_requirements:
    format_validation: true
    pattern_validation: true
    security_scanning: true
    cross_environment_isolation: true
  
  compliance:
    audit_retention_days: 90
    security_scan_frequency: "daily"
    rotation_compliance_check: "weekly"